/*
 * Generated by MTK SP DrvGen Version 03.13.6 for MT6589_NP. Copyright MediaTek Inc. (C) 2013.
 * Sun Mar 06 19:14:50 2016
 * Do Not Modify the File.
 */



#include "pmic_drv.h"



//For PMIC driver use


