/*
 * Generated by MTK SP DrvGen Version 10.03.0 for MT6589_NP. Copyright MediaTek Inc. (C) 2012.
 * Fri Nov 06 20:57:23 2015
 * Do Not Modify the File.
 */



#include "pmic_drv.h"




//For PMIC driver use


